all: geocoordparser.cpp
	g++-4.7 geocoordparser.cpp -o geocoordparser -std=c++11 -Wall 

test: all
	./geocoordparser Tabelle_5a.txt deutsch.dat

mini: mini.cpp
	g++-4.7 mini.cpp -o mini -std=c++11 -Wall


